[[main]]
  name = "The Basics"
  url = "/docs/guides/The Editor/Placing Objects"
  weight = 10

[[main]]
  name = "Triggers"
  url = "/docs/guides/Triggers 1/Trigger Intro"
  weight = 20

[[main]]
  name = "Gameplay"
  url = "/docs/guides/Gameplay 1/Using Gamemodes"
  weight = 30

[[main]]
  name = "Decoration"
  url = "/docs/guides/Deco 1/Using Deco Objects"
  weight = 40

[[social]]
  name = "Discord"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-discord" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M8 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0"></path><path d="M14 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0"></path><path d="M8.5 17c0 1 -1.356 3 -1.832 3c-1.429 0 -2.698 -1.667 -3.333 -3c-.635 -1.667 -.476 -5.833 1.428 -11.5c1.388 -1.015 2.782 -1.34 4.237 -1.5l.975 1.923a11.913 11.913 0 0 1 4.053 0l.972 -1.923c1.5 .16 3.043 .485 4.5 1.5c2 5.667 2.167 9.833 1.5 11.5c-.667 1.333 -2 3 -3.5 3c-.5 0 -2 -2 -2 -3"></path><path d="M7 16.5c3.5 1 6.5 1 10 0"></path></svg>'
  url = "https://discord.gg/gdlevels"
  post = "v0.1.0"
  weight = 20

# [[sidebar_docs]]
#   name = "Guides"
#   pageRef = "/docs/guides"
#   weight = 10
#
# [[sidebar_docs]]
#   name = "Reference"
#   pageRef = "/docs/reference"
#   weight = 20
#
# [[sidebar_docs]]
#   name = "Resources"
#   pageRef = "/docs/resources"
#   weight = 30

[[footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 10

# [[footer]]
#   name = "Terms of Service"
#   url = "/terms/"
#   weight = 20
